### ISSUE TITLE
search/replace

### ISSUE THREAD

**Issue by anntzer** [takluyver/astsearch#3]
It looks like the project is not very active :-) but just in case you're still working on it, here's an idea: allow search/replace with commands of the form (e.g., conversion of nose style tests to pytest style tests) `astsearchreplace 'assert_true(?1)' 'assert ?1'`.  Placeholders would get an index (`?1`) so that the replacement string could refer to them.  Perhaps the code generation part could be implemented as a 2to3 fixer?

**Comment by takluyver** [comment]
Thanks; it's a good idea, but the code for it would have to built on totally different foundations (like 2to3, as you suggest), so I don't see it ever being part of this project. If you haven't already, have a look at [python-modernize](https://github.com/python-modernize/python-modernize) as an example of using 2to3 fixers in a separate project.

**Comment by anntzer** [comment]
My idea was to have an "easy" way to specify replacement patterns using the wildcard syntax that astsearch provides, but I guess the wildcard syntax is only a small part of it.

**Comment by takluyver** [comment]
The wildcard syntax is a pretty big part of it, but all the existing code interprets it to use the `ast` module, which isn't suitable for rewriting code - the data it handles doesn't include comments or formatting, so you'd lose those whenever it modified a file. Changing it to use something like 2to3 would require rewriting almost all the code, I think.

I remembered this discussion about common tools for parsing and refactoring code, which you might be interested in: https://github.com/davidhalter/jedi/issues/630

**Comment by anntzer** [comment]
Thanks.  Feel free to close the issue.

**Comment by takluyver** [comment]
Thanks
