### ISSUE TITLE
How to find all mentions of an attribute?

### ISSUE THREAD

**Issue by vfaronov** [takluyver/astsearch#5]
I want to find all places in my codebase where I refer to an attribute named `baz` on any object. For example:

```
foo.bar.baz = qux
```

Can I do that with ASTsearch?

These don’t work:

```
$ astsearch '?.baz'
$ astsearch '??.baz'
```

Neither does this (not that it would solve my problem):

```
$ astsearch '?.bar.baz'
```

I can find `.bar`, though:

```
$ astsearch '?.bar'
./kjT.py
   1|foo.bar.baz = qux
```

**Comment by takluyver** [comment]
The issue was that it was only finding attribute access with the load context - where you were reading a value, rather than setting or deleting it.

```python
foo.bar.baz = qux # Not found
qux = foo.bar.baz # Found
```

I've just pushed a commit to fix it.

**Comment by vfaronov** [comment]
Thanks!
