### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by kmuehlbauer** [takluyver/astsearch#9]
While trying to stage `astsearch` into `conda-forge` I found the package declared as MIT but no `LICENSE` file. 

What's the best way forward to resolve this?

**Comment by takluyver** [comment]
> What's the best way forward to resolve this?

With `cp` :wink: 

Feel free to add the new LICENSE file to an existing release for conda-forge.

**Comment by kmuehlbauer** [comment]
@takluyver Very much appreciate the immediate response. May I ping you over at conda-forge to have a look at the PR?

**Comment by takluyver** [comment]
Sure, no problem. :-)
